name: Scan Rules DB and Namespaces
on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize

jobs:
  scan_job:
    name: Scanner Registry Action
    runs-on: "ubuntu-latest"

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Scan Registry
        uses: boostsecurityio/scanner-registry-action@dd0703bec01a6d2f420b865ab2cf0a9e13cd38fd
        with:
          api_endpoint: ${{ vars.BOOST_API_ENDPOINT }}
          api_token: ${{ secrets.BOOST_SYSTEM_API_KEY_REGISTRY }}
          docs_url: ${{ vars.BOOST_DOCS_URL }}
